version: "3.8"
services:
  webapp:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/az-pipe
    container_name: django-az-pipe
    hostname: django-dev-az-pipe
    volumes:
       - ./app:/app
    # command: sleep 3600